# Generated by Django 5.2 on 2025-04-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_remove_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='session_key',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
